boson_node:
  trigger_type: SOFTWARE
  cal_path: /home/dcist/camera_ws/src/eeyore/cal/boson_calibration.yaml
  frame_rate: 9
  frame_id: boson
  width: 640
  height: 512
  sensor_name: boson
  video_id: /dev/boson_video
